config/routes.rb
Rails.application.routes.draw do
=begin
  post 'items/create'

  get 'users/show'

  post 'users/show'

  get 'welcome/index'

  get 'welcome/about'
=end

  post 'users/show'

  root 'users#show'

  devise_for :users

  resources :users, only: [:show] do
    resources :items, only: [:create, :destroy]
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :items

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new
    @item.name = params[:item][:name]
    @item.user = current_user


    if @item.save
      flash[:notice] = "item added to todo list"
      redirect_to root_path
    else
      flash.now[:alert] = "there was an error saving the item"
      render :new
    end
  end

  def destroy
    # raise params[:id]

    @item = Item.find_by(id: params[:id])
    if @item.destroy
      flash[:notice] = "item deleted"
      redirect_to root_path
    else
      flash.now[:alert] = "error deleting item"
      render :show
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @items = Item.where(user: current_user)
    @item = Item.new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for @item, url: user_items_path(user_id: @user.id), method: :post do |f| %>
  <div class="form-group">
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter todo" %>
    <%= f.submit "Add Todo", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/items/_item.html.erb
<% @items.each do |item| %>
  <h5><%= item.name %><%= link_to "", user_item_path(@user,item), method: :delete, class: 'glyphicon glyphicon-ok' %></h5>
  <h6><%= distance_of_time_in_words(Time.now-7.days, item.created_at) %> left to finish</h6>
<% end %>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if user_signed_in? %>
    Signed in as: <strong><%= current_user.email %></strong> |
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
    <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
    <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>

  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>
  
<%= yield %>

</body>
</html>

app/views/users/show.html.erb
<% if current_user %>
  <h2><%= current_user.email %>'s todo items</h2>
  <%= render partial: 'items/item', locals: {items: @items} %>
  <%= render partial: 'items/form', locals: {user: @user} %>
<% end %>

<% if !current_user %>s
  <h2>Please sign up or sign in</h2>
<% end %>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1>blocitoff</h1>
  <h3>Welcome to blocitoff, a todo list app</h3>
  <p>
    <%= link_to "sign in", new_user_session_path %> or
    <%= link_to "sign up", new_user_registration_path, class: 'btn' %>
  </p>
</div>